// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyD6dzBf6h64Upcy4znjBd89sZUXDOrmA',
    appId: '1:639736626355:web:bdd56eda5aed5c5ef884c6',
    messagingSenderId: '639736626355',
    projectId: 'autobuddys-app',
    authDomain: 'autobuddys-app.firebaseapp.com',
    storageBucket: 'autobuddys-app.appspot.com',
    measurementId: 'G-N8V9C854D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD81arbNhCR23Cb0Qj6AvBowFAEaL-VlK4',
    appId: '1:639736626355:android:e140efee9c959ff6f884c6',
    messagingSenderId: '639736626355',
    projectId: 'autobuddys-app',
    storageBucket: 'autobuddys-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTiYk0RMkA5w_KAF_vPZ-2P5vPg4bNp1U',
    appId: '1:639736626355:ios:0f58a332c3715c4bf884c6',
    messagingSenderId: '639736626355',
    projectId: 'autobuddys-app',
    storageBucket: 'autobuddys-app.appspot.com',
    androidClientId: '639736626355-e5a6co3ihdmfom8mhtm27tgjne2kuii6.apps.googleusercontent.com',
    iosClientId: '639736626355-4lq0lmpcrrrdgc51cticircvb1qtnc6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.autobuddyAsdApp',
  );
}
